export const QUADRANTS = [
  {
    id: 'q1',
    label: 'Do First',
    action: 'Tackle immediately',
    urgent: true,
    important: true,
    cssVarBg: '--color-q1-bg',
    cssVarBorder: '--color-q1-border',
    cssVarText: '--color-q1-text',
    cssVarBadge: '--color-q1-badge',
  },
  {
    id: 'q2',
    label: 'Schedule',
    action: 'Plan and calendar it',
    urgent: false,
    important: true,
    cssVarBg: '--color-q2-bg',
    cssVarBorder: '--color-q2-border',
    cssVarText: '--color-q2-text',
    cssVarBadge: '--color-q2-badge',
  },
  {
    id: 'q3',
    label: 'Delegate',
    action: 'Hand off if possible',
    urgent: true,
    important: false,
    cssVarBg: '--color-q3-bg',
    cssVarBorder: '--color-q3-border',
    cssVarText: '--color-q3-text',
    cssVarBadge: '--color-q3-badge',
  },
  {
    id: 'q4',
    label: 'Eliminate',
    action: 'Drop or defer',
    urgent: false,
    important: false,
    cssVarBg: '--color-q4-bg',
    cssVarBorder: '--color-q4-border',
    cssVarText: '--color-q4-text',
    cssVarBadge: '--color-q4-badge',
  },
]
